version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/sdk/node"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      node-development:
        dependency-type: "development"
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/sdk/python"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      python-build-and-test:
        patterns: ["*"]

  - package-ecosystem: "gradle"
    directory: "/sdk/kotlin"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      kotlin-build-and-runtime:
        patterns: ["*"]

  - package-ecosystem: "gradle"
    directory: "/sdk/android"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      android-build-and-runtime:
        patterns: ["*"]

  - package-ecosystem: "swift"
    directory: "/sdk/apple"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
