import CDesfire
// Generated by tools/generate.py from split C ABI headers; no protocol implementation.
import Foundation

extension Card {

    /**
     * Call df_get_version once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_version(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_version(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_free_memory once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func free_memory(timeout_ms: UInt32 = 5000) async throws -> UInt32 {
        try await perform { handle in
            var error = df_error()
            var output: UInt32 = 0
            let status = df_free_memory(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return output
        }
    }

    /**
     * Call df_select_application once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func select_application(aid: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_select_application(handle, aid, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_file_ids once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func file_ids(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_file_ids(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_authenticate_standard_aes once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func authenticate_standard_aes(key_number: UInt32, key: Data, timeout_ms: UInt32 = 5000)
        async throws
    {
        try await perform { handle in
            return try withBinary(key) { keyPointer, keySize in
                var error = df_error()
                let status = df_authenticate_standard_aes(
                    handle, key_number, keyPointer, keySize, timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_application_ids once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func application_ids(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_application_ids(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_iso_file_ids once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_file_ids(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_iso_file_ids(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_get_key_settings once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_key_settings(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_key_settings(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_get_key_set_versions once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_key_set_versions(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_key_set_versions(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_get_card_uid once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_card_uid(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_card_uid(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_read_originality_signature once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func read_originality_signature(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_read_originality_signature(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_abort_transaction once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func abort_transaction(timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_abort_transaction(handle, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_format_picc once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func format_picc(timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_format_picc(handle, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_delete_file once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func delete_file(file: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_delete_file(handle, file, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_get_file_settings once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_file_settings(file: UInt32, timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_file_settings(handle, file, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_clear_record_file once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func clear_record_file(file: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_clear_record_file(handle, file, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_get_file_counters once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_file_counters(
        file: UInt32, communication: CommunicationMode, timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_file_counters(
                handle, file, communication.rawValue, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_delete_application once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func delete_application(aid: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_delete_application(handle, aid, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_change_key_settings once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func change_key_settings(settings: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_change_key_settings(handle, settings, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_get_key_version once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_key_version(number: UInt32, key_set: Int32, timeout_ms: UInt32 = 5000)
        async throws -> Data
    {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_key_version(handle, number, key_set, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_initialize_key_set once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func initialize_key_set(key_set: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_initialize_key_set(handle, key_set, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_roll_key_set once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func roll_key_set(key_set: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_roll_key_set(handle, key_set, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_finalize_key_set once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func finalize_key_set(key_set: UInt32, version: UInt32, timeout_ms: UInt32 = 5000)
        async throws
    {
        try await perform { handle in
            var error = df_error()
            let status = df_finalize_key_set(handle, key_set, version, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_read_data once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func read_data(
        file: UInt32, offset: UInt32, length: UInt32, communication: CommunicationMode,
        timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_read_data(
                handle, file, offset, length, communication.rawValue, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_write_data once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func write_data(
        file: UInt32, offset: UInt32, data: Data, communication: CommunicationMode,
        timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                let status = df_write_data(
                    handle, file, offset, dataPointer, dataSize, communication.rawValue, timeout_ms,
                    &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_write_record once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func write_record(
        file: UInt32, offset: UInt32, data: Data, communication: CommunicationMode,
        timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                let status = df_write_record(
                    handle, file, offset, dataPointer, dataSize, communication.rawValue, timeout_ms,
                    &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_read_records once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func read_records(
        file: UInt32, first: UInt32, count: UInt32, communication: CommunicationMode,
        timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_read_records(
                handle, file, first, count, communication.rawValue, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_update_record once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func update_record(
        file: UInt32, record: UInt32, offset: UInt32, data: Data, communication: CommunicationMode,
        timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                let status = df_update_record(
                    handle, file, record, offset, dataPointer, dataSize, communication.rawValue,
                    timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_credit once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func credit(
        file: UInt32, amount: UInt32, communication: CommunicationMode, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_credit(handle, file, amount, communication.rawValue, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_debit once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func debit(
        file: UInt32, amount: UInt32, communication: CommunicationMode, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_debit(handle, file, amount, communication.rawValue, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_limited_credit once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func limited_credit(
        file: UInt32, amount: UInt32, communication: CommunicationMode, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_limited_credit(
                handle, file, amount, communication.rawValue, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_get_value once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_value(file: UInt32, communication: CommunicationMode, timeout_ms: UInt32 = 5000)
        async throws -> Int32
    {
        try await perform { handle in
            var error = df_error()
            var output: Int32 = 0
            let status = df_get_value(
                handle, file, communication.rawValue, timeout_ms, &output, &error)
            try checkNative(status, error)
            return output
        }
    }

    /**
     * Call df_commit_transaction once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func commit_transaction(return_mac: UInt32, timeout_ms: UInt32 = 5000) async throws
        -> Data
    {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_commit_transaction(handle, return_mac, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_commit_reader_id once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func commit_reader_id(reader_id: Data, timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            return try withBinary(reader_id) { reader_idPointer, reader_idSize in
                var error = df_error()
                var output: OpaquePointer?
                defer { df_buffer_free(output) }
                let status = df_commit_reader_id(
                    handle, reader_idPointer, reader_idSize, timeout_ms, &output, &error)
                try checkNative(status, error)
                return try ownedBuffer(output)
            }
        }
    }

    /**
     * Call df_create_application once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func create_application(
        aid: UInt32, key_settings: UInt32, key_count: UInt32, iso_id: Int32, df_name: Data,
        timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(df_name) { df_namePointer, df_nameSize in
                var error = df_error()
                let status = df_create_application(
                    handle, aid, key_settings, key_count, iso_id, df_namePointer, df_nameSize,
                    timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_create_data_file once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func create_data_file(
        file: UInt32, length: UInt32, communication: CommunicationMode, access_rights: UInt32,
        iso_id: Int32, backup: UInt32, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_create_data_file(
                handle, file, length, communication.rawValue, access_rights, iso_id, backup,
                timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_create_value_file once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func create_value_file(
        file: UInt32, lower_limit: Int32, upper_limit: Int32, initial_value: Int32,
        communication: CommunicationMode, access_rights: UInt32, limited_credit: UInt32,
        free_get_value: UInt32, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_create_value_file(
                handle, file, lower_limit, upper_limit, initial_value, communication.rawValue,
                access_rights, limited_credit, free_get_value, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_create_record_file once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func create_record_file(
        file: UInt32, record_size: UInt32, maximum_records: UInt32,
        communication: CommunicationMode, access_rights: UInt32, iso_id: Int32, cyclic: UInt32,
        timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_create_record_file(
                handle, file, record_size, maximum_records, communication.rawValue, access_rights,
                iso_id, cyclic, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_change_file_settings once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func change_file_settings(
        file: UInt32, communication: CommunicationMode, access_rights: UInt32,
        command_communication: CommunicationMode, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_change_file_settings(
                handle, file, communication.rawValue, access_rights, command_communication.rawValue,
                timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_create_transaction_mac_file once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func create_transaction_mac_file(
        file: UInt32, access_rights: UInt32, key: Data, version: UInt32, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(key) { keyPointer, keySize in
                var error = df_error()
                let status = df_create_transaction_mac_file(
                    handle, file, access_rights, keyPointer, keySize, version, timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_change_aes_key once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func change_aes_key(
        number: UInt32, new_key: Data, version: UInt32, authenticated_key: UInt32, old_key: Data,
        key_set: Int32, picc_master: UInt32, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(new_key) { new_keyPointer, new_keySize in
                return try withBinary(old_key) { old_keyPointer, old_keySize in
                    var error = df_error()
                    let status = df_change_aes_key(
                        handle, number, new_keyPointer, new_keySize, version, authenticated_key,
                        old_keyPointer, old_keySize, key_set, picc_master, timeout_ms, &error)
                    try checkNative(status, error)
                }
            }
        }
    }

    /**
     * Call df_iso_select_file once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_select_file(
        identifier: UInt32, selection: UInt32, response: UInt32, timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_iso_select_file(
                handle, identifier, selection, response, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_iso_select_df_name once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_select_df_name(name: Data, response: UInt32, timeout_ms: UInt32 = 5000)
        async throws -> Data
    {
        try await perform { handle in
            return try withBinary(name) { namePointer, nameSize in
                var error = df_error()
                var output: OpaquePointer?
                defer { df_buffer_free(output) }
                let status = df_iso_select_df_name(
                    handle, namePointer, nameSize, response, timeout_ms, &output, &error)
                try checkNative(status, error)
                return try ownedBuffer(output)
            }
        }
    }

    /**
     * Call df_iso_read_binary once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_read_binary(
        short_identifier: Int32, offset: UInt32, length: UInt32, timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_iso_read_binary(
                handle, short_identifier, offset, length, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_iso_update_binary once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_update_binary(
        short_identifier: Int32, offset: UInt32, data: Data, timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                var output: OpaquePointer?
                defer { df_buffer_free(output) }
                let status = df_iso_update_binary(
                    handle, short_identifier, offset, dataPointer, dataSize, timeout_ms, &output,
                    &error)
                try checkNative(status, error)
                return try ownedBuffer(output)
            }
        }
    }

    /**
     * Call df_iso_read_records once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_read_records(
        record: UInt32, short_identifier: UInt32, selection: UInt32, length: UInt32,
        timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_iso_read_records(
                handle, record, short_identifier, selection, length, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_iso_append_record once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_append_record(short_identifier: UInt32, data: Data, timeout_ms: UInt32 = 5000)
        async throws -> Data
    {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                var output: OpaquePointer?
                defer { df_buffer_free(output) }
                let status = df_iso_append_record(
                    handle, short_identifier, dataPointer, dataSize, timeout_ms, &output, &error)
                try checkNative(status, error)
                return try ownedBuffer(output)
            }
        }
    }

    /**
     * Call df_iso_get_challenge once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_get_challenge(length: UInt32, timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_iso_get_challenge(handle, length, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_iso_external_authenticate once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_external_authenticate(
        number: UInt32, application: UInt32, algorithm: UInt32, data: Data,
        timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                var output: OpaquePointer?
                defer { df_buffer_free(output) }
                let status = df_iso_external_authenticate(
                    handle, number, application, algorithm, dataPointer, dataSize, timeout_ms,
                    &output, &error)
                try checkNative(status, error)
                return try ownedBuffer(output)
            }
        }
    }

    /**
     * Call df_iso_internal_authenticate once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_internal_authenticate(
        number: UInt32, application: UInt32, algorithm: UInt32, data: Data,
        timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                var output: OpaquePointer?
                defer { df_buffer_free(output) }
                let status = df_iso_internal_authenticate(
                    handle, number, application, algorithm, dataPointer, dataSize, timeout_ms,
                    &output, &error)
                try checkNative(status, error)
                return try ownedBuffer(output)
            }
        }
    }

    /**
     * Call df_authenticate_iso_aes once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func authenticate_iso_aes(
        number: UInt32, application: UInt32, key: Data, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(key) { keyPointer, keySize in
                var error = df_error()
                let status = df_authenticate_iso_aes(
                    handle, number, application, keyPointer, keySize, timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_get_df_names once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_df_names(timeout_ms: UInt32 = 5000) async throws -> Data {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_df_names(handle, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_reset_authentication once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func reset_authentication() async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_reset_authentication(handle, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_restore_transfer once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func restore_transfer(
        target_file: UInt32, source_file: UInt32, communication: CommunicationMode,
        timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_restore_transfer(
                handle, target_file, source_file, communication.rawValue, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_create_delegated_application once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func create_delegated_application(
        aid: UInt32, key_settings: UInt32, number_of_keys: UInt32, slot: UInt32,
        slot_version: UInt32, quota_limit: UInt32, iso_file_identifiers: UInt32,
        key_settings3: Int32, iso_id: Int32, df_name: Data, encrypted_default_key: Data,
        dam_mac: Data, timeout_ms: UInt32 = 5000
    ) async throws {
        try await perform { handle in
            return try withBinary(df_name) { df_namePointer, df_nameSize in
                return try withBinary(encrypted_default_key) {
                    encrypted_default_keyPointer, encrypted_default_keySize in
                    return try withBinary(dam_mac) { dam_macPointer, dam_macSize in
                        var error = df_error()
                        let status = df_create_delegated_application(
                            handle, aid, key_settings, number_of_keys, slot, slot_version,
                            quota_limit, iso_file_identifiers, key_settings3, iso_id,
                            df_namePointer, df_nameSize, encrypted_default_keyPointer,
                            encrypted_default_keySize, dam_macPointer, dam_macSize, timeout_ms,
                            &error)
                        try checkNative(status, error)
                    }
                }
            }
        }
    }

    /**
     * Call df_delete_delegated_application once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func delete_delegated_application(aid: UInt32, dam_mac: Data, timeout_ms: UInt32 = 5000)
        async throws
    {
        try await perform { handle in
            return try withBinary(dam_mac) { dam_macPointer, dam_macSize in
                var error = df_error()
                let status = df_delete_delegated_application(
                    handle, aid, dam_macPointer, dam_macSize, timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_get_card_uid_variant once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func get_card_uid_variant(option: UInt32, timeout_ms: UInt32 = 5000) async throws -> Data
    {
        try await perform { handle in
            var error = df_error()
            var output: OpaquePointer?
            defer { df_buffer_free(output) }
            let status = df_get_card_uid_variant(handle, option, timeout_ms, &output, &error)
            try checkNative(status, error)
            return try ownedBuffer(output)
        }
    }

    /**
     * Call df_set_capability_configuration once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func set_capability_configuration(capabilities: Data, timeout_ms: UInt32 = 5000)
        async throws
    {
        try await perform { handle in
            return try withBinary(capabilities) { capabilitiesPointer, capabilitiesSize in
                var error = df_error()
                let status = df_set_capability_configuration(
                    handle, capabilitiesPointer, capabilitiesSize, timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_set_default_aes_key once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func set_default_aes_key(key: Data, key_version: UInt32, timeout_ms: UInt32 = 5000)
        async throws
    {
        try await perform { handle in
            return try withBinary(key) { keyPointer, keySize in
                var error = df_error()
                let status = df_set_default_aes_key(
                    handle, keyPointer, keySize, key_version, timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_set_ats once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func set_ats(ats: Data, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            return try withBinary(ats) { atsPointer, atsSize in
                var error = df_error()
                let status = df_set_ats(handle, atsPointer, atsSize, timeout_ms, &error)
                try checkNative(status, error)
            }
        }
    }

    /**
     * Call df_set_atqa once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func set_atqa(atqa: UInt32, timeout_ms: UInt32 = 5000) async throws {
        try await perform { handle in
            var error = df_error()
            let status = df_set_atqa(handle, atqa, timeout_ms, &error)
            try checkNative(status, error)
        }
    }

    /**
     * Call df_iso_update_record once on the card queue; timeout is milliseconds.
     * Binary inputs are borrowed only during the call; results own their storage.
     */
    public func iso_update_record(
        instruction: UInt32, record: UInt32, short_identifier: UInt32, reference_control: UInt32,
        data: Data, timeout_ms: UInt32 = 5000
    ) async throws -> Data {
        try await perform { handle in
            return try withBinary(data) { dataPointer, dataSize in
                var error = df_error()
                var output: OpaquePointer?
                defer { df_buffer_free(output) }
                let status = df_iso_update_record(
                    handle, instruction, record, short_identifier, reference_control, dataPointer,
                    dataSize, timeout_ms, &output, &error)
                try checkNative(status, error)
                return try ownedBuffer(output)
            }
        }
    }
}

/**
 * Generated native operation names used for checked ABI coverage.
 */
public let supportedNativeOperations: [String] = [
    "df_get_version",
    "df_free_memory",
    "df_select_application",
    "df_file_ids",
    "df_authenticate_standard_aes",
    "df_application_ids",
    "df_iso_file_ids",
    "df_get_key_settings",
    "df_get_key_set_versions",
    "df_get_card_uid",
    "df_read_originality_signature",
    "df_abort_transaction",
    "df_format_picc",
    "df_delete_file",
    "df_get_file_settings",
    "df_clear_record_file",
    "df_get_file_counters",
    "df_delete_application",
    "df_change_key_settings",
    "df_get_key_version",
    "df_initialize_key_set",
    "df_roll_key_set",
    "df_finalize_key_set",
    "df_read_data",
    "df_write_data",
    "df_write_record",
    "df_read_records",
    "df_update_record",
    "df_credit",
    "df_debit",
    "df_limited_credit",
    "df_get_value",
    "df_commit_transaction",
    "df_commit_reader_id",
    "df_create_application",
    "df_create_data_file",
    "df_create_value_file",
    "df_create_record_file",
    "df_change_file_settings",
    "df_create_transaction_mac_file",
    "df_change_aes_key",
    "df_iso_select_file",
    "df_iso_select_df_name",
    "df_iso_read_binary",
    "df_iso_update_binary",
    "df_iso_read_records",
    "df_iso_append_record",
    "df_iso_get_challenge",
    "df_iso_external_authenticate",
    "df_iso_internal_authenticate",
    "df_authenticate_iso_aes",
    "df_get_df_names",
    "df_reset_authentication",
    "df_restore_transfer",
    "df_create_delegated_application",
    "df_delete_delegated_application",
    "df_get_card_uid_variant",
    "df_set_capability_configuration",
    "df_set_default_aes_key",
    "df_set_ats",
    "df_set_atqa",
    "df_iso_update_record",
]
