"""Generate typed Swift managed methods from the split C ABI headers."""

from pathlib import Path
import re
import subprocess


def generate() -> None:
    """Write deterministic Swift wrappers and a public C ABI operation coverage list."""
    package = Path(__file__).resolve().parents[1]
    root = package.parents[1]
    header = "\n".join(
        path.read_text()
        for path in sorted((root / "c-api/include/desfire").glob("*.h"))
    )
    functions = re.findall(r"DF_API int32_t (df_\w+)\((.*?)\);", header, re.S)
    excluded = {"df_open", "df_close", "df_reset", "df_cancel", "df_notify_state_change"}
    manually_wrapped = {
        "df_authenticate_ev2_first_aes",
        "df_authenticate_ev2_first_aes_provider",
        "df_authenticate_ev2_first_aes_with_capabilities",
        "df_authenticate_ev2_first_aes_with_capabilities_provider",
        "df_authenticate_ev2_non_first_aes",
        "df_authenticate_ev2_non_first_aes_provider",
        "df_authenticate_standard_aes_provider",
        "df_authenticate_iso_aes_provider",
        "df_change_aes_key_provider",
        "df_create_transaction_mac_file_provider",
        "df_execute_transaction",
        "df_get_delegated_application_info",
        "df_set_default_aes_key_provider",
        "df_set_picc_configuration",
    }
    source = ["// Generated by tools/generate.py from split C ABI headers; no protocol implementation.",
              "import Foundation", "import CDesfire", "", "public extension Card {"]
    operation_names = []
    for name, declaration in functions:
        compact_declaration = " ".join(declaration.split())
        if name in excluded or name in manually_wrapped or not compact_declaration.startswith("df_card "):
            continue
        parameters = [re.sub(r"\s*\*\s*", "*", " ".join(part.split()))
                      for part in declaration.split(",")][1:-1]
        result = "void"
        for prefix, kind in [("df_buffer**", "bytes"), ("uint32_t*", "u32"),
                             ("int32_t*", "i32")]:
            if parameters and parameters[-1].startswith(prefix):
                parameters.pop()
                result = kind
                break
        signature = []
        call_arguments = ["handle"]
        binary = []
        index = 0
        while index < len(parameters):
            parameter = parameters[index]
            if parameter.startswith("const uint8_t*"):
                argument = parameter.removeprefix("const uint8_t*").strip()
                if not parameters[index + 1].startswith("size_t "):
                    raise ValueError(f"Unpaired binary argument in {name}")
                signature.append(f"{argument}: Data")
                binary.append(argument)
                call_arguments.extend([f"{argument}Pointer", f"{argument}Size"])
                index += 2
            else:
                parts = parameter.split()
                if len(parts) != 2:
                    raise ValueError(f"Unsupported managed parameter in {name}: {parameter}")
                kind, argument = parts
                swift_type = {"uint32_t": "UInt32", "int32_t": "Int32"}[kind]
                if argument in {"communication", "command_communication"}:
                    signature.append(f"{argument}: CommunicationMode")
                    call_arguments.append(argument + ".rawValue")
                else:
                    default = " = 5000" if argument == "timeout_ms" else ""
                    signature.append(f"{argument}: {swift_type}{default}")
                    call_arguments.append(argument)
                index += 1
        output_type = {"void": "Void", "bytes": "Data", "u32": "UInt32", "i32": "Int32"}[result]
        operation_names.append(name)
        source.extend(["", f"    /// Call {name} once on the card queue; timeout is milliseconds.",
                       "    /// Binary inputs are borrowed only during the call; results own their storage.",
                       f"    func {name[3:]}({', '.join(signature)}) async throws -> {output_type} {{",
                       "        try await perform { handle in"])
        indent = "            "
        for argument in binary:
            source.append(indent + f"return try withBinary({argument}) {{ {argument}Pointer, {argument}Size in")
            indent += "    "
        source.append(indent + "var error = df_error()")
        if result == "bytes":
            source.extend([indent + "var output: OpaquePointer?", indent + "defer { df_buffer_free(output) }"])
        elif result != "void":
            source.append(indent + f"var output: {output_type} = 0")
        if result != "void":
            call_arguments.append("&output")
        call_arguments.append("&error")
        source.extend([indent + f"let status = {name}({', '.join(call_arguments)})",
                       indent + "try checkNative(status, error)"])
        if result == "bytes":
            source.append(indent + "return try ownedBuffer(output)")
        elif result != "void":
            source.append(indent + "return output")
        for _ in binary:
            indent = indent[:-4]
            source.append(indent + "}")
        source.extend(["        }", "    }"])
    source.extend(["}", "", "/// Generated native operation names used for checked ABI coverage.",
                   "public let supportedNativeOperations: [String] = ["])
    source.extend(f'    "{name}",' for name in operation_names)
    source.extend(["]", ""])
    documented = []
    index = 0
    while index < len(source):
        line = source[index]
        if line.lstrip().startswith("///"):
            indent = line[:len(line) - len(line.lstrip())]
            documented.append(indent + "/**")
            while index < len(source) and source[index].lstrip().startswith("///"):
                documented.append(indent + " * " + source[index].lstrip()[3:].lstrip())
                index += 1
            documented.append(indent + " */")
        else:
            documented.append(line)
            index += 1
    output = package / "Sources/DesfireEV3/Operations.swift"
    output.write_text("\n".join(documented) + "\n")
    subprocess.run(["swift", "format", "format", "--configuration", str(package / ".swift-format"),
                    "--in-place", str(output)], check=True)


if __name__ == "__main__":
    generate()
